apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    name: webapp
spec:
  containers:
    - name: webapp
      image: kodekloud/event-simulator
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: test-mount
          mountPath: /log
  volumes:
    - name: test-mount
      hostPath:
        path: /var/log/webapp
