apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test-secret-pod
spec:
  selector:
    matchLabels:
      app: deployment-test-secret-pod
  template:
    metadata:
      labels:
        app: deployment-test-secret-pod
    spec:
      containers:
        - name: deployment-test-secret-pod
          image: busybox
          command: ["sh", "-c", "echo -n '$(evn-test-secret)' | base64 -d"] # Chạy giải mã base64
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: evn-test-secret
              valueFrom:
                secretKeyRef:
                  name: secret-test
                  key: user
