apiVersion: v1
kind: Pod
metadata:
  name: myapp-secret
  labels:
    name: myapp-secret
spec:
  containers:
  - name: myapp-secret-container
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["sh", "-c", "echo $(evn-test-secret)"]
    env:
      - name:  evn-test-secret
        valueFrom:
          secretKeyRef:
            name:  secret-test
            key:  demo
