apiVersion: v1
kind: Pod
metadata:
  name: myapp-secret
spec:
  containers:
  - name: myapp-secret
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["sh", "-c", "echo -n '$(evn-test-secret)' | base64 -d"] # Chạy giải mã base64
    env:
      - name:  evn-test-secret
        valueFrom:
          secretKeyRef:
            name:  secret-test
            key:  user
