apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
    - name: myapp-test-config
      image: busybox
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      command: ["sh", "-c", "echo $(config_map_key1) $(config_map_key2)"]
      env:
        - name: config_map_key1
          valueFrom:
            configMapKeyRef:
              name: test-configmap
              key: env_text1
        - name: config_map_key2
          valueFrom:
            configMapKeyRef:
              name: test-configmap
              key: env_text1
